export interface EmojiEntry {
  char: string
  name: string
}

/** A curated set of common emoji, grouped loosely by category (order shown in the picker). */
export const EMOJI_LIST: EmojiEntry[] = [
  // smileys
  { char: '😀', name: 'grinning' }, { char: '😃', name: 'smiley' }, { char: '😄', name: 'smile' },
  { char: '😁', name: 'grin' }, { char: '😆', name: 'laughing' }, { char: '😅', name: 'sweat_smile' },
  { char: '🤣', name: 'rofl' }, { char: '😂', name: 'joy' }, { char: '🙂', name: 'slight_smile' },
  { char: '🙃', name: 'upside_down' }, { char: '😉', name: 'wink' }, { char: '😊', name: 'blush' },
  { char: '😇', name: 'innocent' }, { char: '🥰', name: 'love' }, { char: '😍', name: 'heart_eyes' },
  { char: '🤩', name: 'star_struck' }, { char: '😘', name: 'kiss' }, { char: '😗', name: 'kissing' },
  { char: '😋', name: 'yum' }, { char: '😛', name: 'tongue' }, { char: '😜', name: 'wink_tongue' },
  { char: '🤪', name: 'zany' }, { char: '😝', name: 'squint_tongue' }, { char: '🤑', name: 'money_mouth' },
  { char: '🤗', name: 'hug' }, { char: '🤭', name: 'giggle' }, { char: '🤫', name: 'shush' },
  { char: '🤔', name: 'thinking' }, { char: '🤐', name: 'zipper_mouth' }, { char: '🤨', name: 'raised_eyebrow' },
  { char: '😐', name: 'neutral' }, { char: '😑', name: 'expressionless' }, { char: '😶', name: 'no_mouth' },
  { char: '😏', name: 'smirk' }, { char: '😒', name: 'unamused' }, { char: '🙄', name: 'eye_roll' },
  { char: '😬', name: 'grimacing' }, { char: '🤥', name: 'lying' }, { char: '😌', name: 'relieved' },
  { char: '😔', name: 'pensive' }, { char: '😪', name: 'sleepy' }, { char: '🤤', name: 'drool' },
  { char: '😴', name: 'sleep' }, { char: '😷', name: 'mask' }, { char: '🤒', name: 'thermometer' },
  { char: '🤕', name: 'head_bandage' }, { char: '🤢', name: 'nauseated' }, { char: '🤮', name: 'vomit' },
  { char: '🤧', name: 'sneeze' }, { char: '🥵', name: 'hot' }, { char: '🥶', name: 'cold' },
  { char: '🥴', name: 'woozy' }, { char: '😵', name: 'dizzy' }, { char: '🤯', name: 'exploding_head' },
  { char: '🤠', name: 'cowboy' }, { char: '🥳', name: 'party' }, { char: '😎', name: 'sunglasses' },
  { char: '🤓', name: 'nerd' }, { char: '🧐', name: 'monocle' }, { char: '😕', name: 'confused' },
  { char: '😟', name: 'worried' }, { char: '🙁', name: 'frown' }, { char: '☹️', name: 'frowning' },
  { char: '😮', name: 'open_mouth' }, { char: '😯', name: 'hushed' }, { char: '😲', name: 'astonished' },
  { char: '😳', name: 'flushed' }, { char: '🥺', name: 'pleading' }, { char: '😦', name: 'frowning_open' },
  { char: '😧', name: 'anguished' }, { char: '😨', name: 'fearful' }, { char: '😰', name: 'anxious' },
  { char: '😥', name: 'sad_relieved' }, { char: '😢', name: 'cry' }, { char: '😭', name: 'sob' },
  { char: '😱', name: 'scream' }, { char: '😖', name: 'confounded' }, { char: '😣', name: 'persevere' },
  { char: '😞', name: 'disappointed' }, { char: '😓', name: 'sweat' }, { char: '😩', name: 'weary' },
  { char: '😫', name: 'tired' }, { char: '🥱', name: 'yawn' }, { char: '😤', name: 'triumph' },
  { char: '😡', name: 'rage' }, { char: '😠', name: 'angry' }, { char: '🤬', name: 'cursing' },
  { char: '😈', name: 'imp' }, { char: '👿', name: 'devil' }, { char: '💀', name: 'skull' },
  { char: '☠️', name: 'skull_crossbones' }, { char: '💩', name: 'poop' }, { char: '🤡', name: 'clown' },
  { char: '👹', name: 'ogre' }, { char: '👺', name: 'goblin' }, { char: '👻', name: 'ghost' },
  { char: '👽', name: 'alien' }, { char: '🤖', name: 'robot' },
  // gestures / hands
  { char: '👍', name: 'thumbsup' }, { char: '👎', name: 'thumbsdown' }, { char: '👌', name: 'ok_hand' },
  { char: '✌️', name: 'peace' }, { char: '🤞', name: 'crossed_fingers' }, { char: '🤟', name: 'love_you' },
  { char: '🤘', name: 'rock_on' }, { char: '👊', name: 'fist_bump' }, { char: '✊', name: 'fist' },
  { char: '👏', name: 'clap' }, { char: '🙌', name: 'raised_hands' }, { char: '👐', name: 'open_hands' },
  { char: '🤲', name: 'palms_up' }, { char: '🙏', name: 'pray' }, { char: '🤝', name: 'handshake' },
  { char: '💪', name: 'muscle' }, { char: '🫡', name: 'salute' }, { char: '👋', name: 'wave' },
  { char: '🤙', name: 'call_me' }, { char: '👆', name: 'point_up' }, { char: '👇', name: 'point_down' },
  { char: '👈', name: 'point_left' }, { char: '👉', name: 'point_right' }, { char: '🖕', name: 'middle_finger' },
  { char: '✋', name: 'raised_hand' }, { char: '🤚', name: 'back_hand' },
  // hearts / symbols
  { char: '❤️', name: 'heart' }, { char: '🧡', name: 'orange_heart' }, { char: '💛', name: 'yellow_heart' },
  { char: '💚', name: 'green_heart' }, { char: '💙', name: 'blue_heart' }, { char: '💜', name: 'purple_heart' },
  { char: '🖤', name: 'black_heart' }, { char: '🤍', name: 'white_heart' }, { char: '🤎', name: 'brown_heart' },
  { char: '💔', name: 'broken_heart' }, { char: '❣️', name: 'heart_exclamation' }, { char: '💕', name: 'two_hearts' },
  { char: '💞', name: 'revolving_hearts' }, { char: '💓', name: 'heartbeat' }, { char: '💗', name: 'growing_heart' },
  { char: '💖', name: 'sparkling_heart' }, { char: '💘', name: 'cupid' }, { char: '💝', name: 'gift_heart' },
  { char: '🔥', name: 'fire' }, { char: '✨', name: 'sparkles' }, { char: '⭐', name: 'star' },
  { char: '🌟', name: 'star2' }, { char: '💫', name: 'dizzy_star' }, { char: '💥', name: 'boom' },
  { char: '💯', name: '100' }, { char: '💢', name: 'anger' }, { char: '💦', name: 'sweat_drops' },
  { char: '💨', name: 'dash' }, { char: '🕳️', name: 'hole' }, { char: '💣', name: 'bomb' },
  { char: '❗', name: 'exclamation' }, { char: '❓', name: 'question' }, { char: '‼️', name: 'double_exclamation' },
  { char: '⁉️', name: 'interrobang' }, { char: '💤', name: 'zzz' },
  // party / celebration
  { char: '🎉', name: 'tada' }, { char: '🎊', name: 'confetti' }, { char: '🎁', name: 'gift' },
  { char: '🏆', name: 'trophy' }, { char: '🥇', name: 'gold_medal' }, { char: '🎂', name: 'birthday' },
  { char: '🍾', name: 'champagne' }, { char: '🎈', name: 'balloon' },
  // animals
  { char: '🐶', name: 'dog' }, { char: '🐱', name: 'cat' }, { char: '🐭', name: 'mouse' },
  { char: '🐹', name: 'hamster' }, { char: '🐰', name: 'rabbit' }, { char: '🦊', name: 'fox' },
  { char: '🐻', name: 'bear' }, { char: '🐼', name: 'panda' }, { char: '🐨', name: 'koala' },
  { char: '🐯', name: 'tiger' }, { char: '🦁', name: 'lion' }, { char: '🐸', name: 'frog' },
  { char: '🐵', name: 'monkey' }, { char: '🐔', name: 'chicken' }, { char: '🐧', name: 'penguin' },
  { char: '🐦', name: 'bird' }, { char: '🦆', name: 'duck' }, { char: '🦉', name: 'owl' },
  { char: '🐴', name: 'horse' }, { char: '🦄', name: 'unicorn' }, { char: '🐝', name: 'bee' },
  { char: '🦋', name: 'butterfly' }, { char: '🐌', name: 'snail' }, { char: '🐢', name: 'turtle' },
  { char: '🐍', name: 'snake' }, { char: '🐙', name: 'octopus' }, { char: '🦀', name: 'crab' },
  { char: '🐬', name: 'dolphin' }, { char: '🐳', name: 'whale' }, { char: '🦈', name: 'shark' },
  // food / drink
  { char: '🍕', name: 'pizza' }, { char: '🍔', name: 'burger' }, { char: '🍟', name: 'fries' },
  { char: '🌭', name: 'hotdog' }, { char: '🍿', name: 'popcorn' }, { char: '🍩', name: 'donut' },
  { char: '🍪', name: 'cookie' }, { char: '🍦', name: 'ice_cream' }, { char: '🍫', name: 'chocolate' },
  { char: '🍎', name: 'apple' }, { char: '🍌', name: 'banana' }, { char: '🍇', name: 'grapes' },
  { char: '🍓', name: 'strawberry' }, { char: '🍉', name: 'watermelon' }, { char: '🥑', name: 'avocado' },
  { char: '☕', name: 'coffee' }, { char: '🍺', name: 'beer' }, { char: '🍻', name: 'cheers' },
  { char: '🍷', name: 'wine' }, { char: '🥤', name: 'drink' },
  // objects / activities
  { char: '🎮', name: 'game_controller' }, { char: '🕹️', name: 'joystick' }, { char: '🎲', name: 'dice' },
  { char: '🎯', name: 'dart' }, { char: '🎸', name: 'guitar' }, { char: '🎧', name: 'headphones' },
  { char: '🎤', name: 'microphone' }, { char: '📺', name: 'tv' }, { char: '💻', name: 'laptop' },
  { char: '🖥️', name: 'desktop' }, { char: '📱', name: 'phone' }, { char: '📷', name: 'camera' },
  { char: '💡', name: 'bulb' }, { char: '🔔', name: 'bell' }, { char: '🔕', name: 'no_bell' },
  { char: '🔒', name: 'lock' }, { char: '🔓', name: 'unlock' }, { char: '⚔️', name: 'crossed_swords' },
  { char: '🛡️', name: 'shield' }, { char: '⚡', name: 'zap' }, { char: '🌈', name: 'rainbow' },
  { char: '☀️', name: 'sun' }, { char: '🌙', name: 'moon' }, { char: '⭐', name: 'star3' },
  { char: '☁️', name: 'cloud' }, { char: '❄️', name: 'snowflake' }, { char: '⛄', name: 'snowman' },
  // check/cross/arrows
  { char: '✅', name: 'check' }, { char: '☑️', name: 'checkbox' }, { char: '✔️', name: 'check_mark' },
  { char: '❌', name: 'cross' }, { char: '⭕', name: 'circle' }, { char: '➡️', name: 'arrow_right' },
  { char: '⬅️', name: 'arrow_left' }, { char: '⬆️', name: 'arrow_up' }, { char: '⬇️', name: 'arrow_down' },
  { char: '🔄', name: 'reload' }, { char: '🔁', name: 'repeat' }, { char: '🆗', name: 'ok_sign' },
  { char: '🆕', name: 'new' }, { char: '🚫', name: 'no_entry' }, { char: '⚠️', name: 'warning' },
  // flags-ish/misc
  { char: '🏳️‍🌈', name: 'pride_flag' }, { char: '🇺🇦', name: 'ukraine' }
]
